import{a as L,S as w,i as u}from"./assets/vendor-b11e2a50.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();async function g(e,n=1,r=12){const t=`https://pixabay.com/api/?${new URLSearchParams({key:"44785846-fbfadd775113e3685d7630ccf",q:e,image_type:"photo",orientation:"horizontal",safesearch:!1,per_page:r,page:n})}`;return await L.get(t).then(o=>(console.log(o),{images:o.data.hits,totalImages:o.data.totalHits})).catch(o=>console.log(o))}function I(){const e=document.getElementById("gallery");e.innerHTML=""}let d;function f(e){document.getElementById("gallery").insertAdjacentHTML("beforeend",e.map(r=>`
        <div class="gallery-item">
            <a href="${r.largeImageURL}">
                <img src="${r.webformatURL}" alt="${r.tags}" />
            </a>
            <div class="info">
                <p><strong>Likes:</strong><br>${r.likes}</p>
                <p><strong>Views:</strong><br>${r.views}</p>
                <p><strong>Comments:</strong><br>${r.comments}</p>
                <p><strong>Downloads:</strong><br>${r.downloads}</p>
            </div>
        </div>`).join("")),d?d.refresh():d=new w(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function m(){const e=document.getElementById("loader");e.style.display="inline-block"}function y(){const e=document.getElementById("loader");e.style.display="none"}function b(){u.warning({title:"Not found",message:"Sorry, there are no images matching search query. Please try again!",position:"topRight"})}function p(){u.info({title:"End of List",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function h(e){u.error({title:"Error",message:e.message,position:"topRight"})}function E(){const e=document.getElementById("loadMoreButton");e.style.display="inline-block"}function B(){const e=document.getElementById("loadMoreButton");e.style.display="none"}function M(){const e=document.querySelector(".gallery-item");if(!e)return;const n=e.getBoundingClientRect().height*2;window.scrollBy({top:n,behavior:"smooth"})}let a="sert",s=1;const i=15;document.getElementById("searchButton").addEventListener("click",async()=>{if(s=1,a=document.getElementById("searchInput").value.trim(),a!==""){I();try{m();const{images:e,totalImages:n}=await g(a,s,i);e.length===0?b():(f(e),E()),s*i>=n&&(B(),p())}catch(e){h(e)}finally{y()}}});document.getElementById("loadMoreButton").addEventListener("click",async()=>{s++;try{m();const{images:e,totalImages:n}=await g(a,s,i);e.length===0?showNoResultsMessage():(f(e),M(),s*i>=n&&(B(),p()))}catch(e){h(e)}finally{y()}});
//# sourceMappingURL=commonHelpers.js.map
